In [1]:
import numpy as np
import pandas as pd

import os
from pathlib import Path
from urllib.request import urlretrieve
from urllib.error import HTTPError, URLError
from zipfile import ZipFile

In [2]:
CITIBIKE_INDEX_URL = "https://s3.amazonaws.com/tripdata"
OUTPUT_DIR = "../data"
PERIOD = "202606"

In [3]:
file_name = f"JC-{PERIOD}-citibike-tripdata.zip"
url = f"{CITIBIKE_INDEX_URL}/{file_name}"
url

'https://s3.amazonaws.com/tripdata/JC-202606-citibike-tripdata.zip'

In [5]:
def period_iterator(year:list,start_m:int, stop_m:int)->list:
    """
    
    """
    YEAR = year
    MONTH =  [str(i+1) if i+1>9 else "0" + str(i+1) for i in range(start_m, stop_m)]

    periods = []

    for i in YEAR:
        for j in MONTH:
            k = i+j
            periods.append(k)
    # print(periods)
    return periods

In [6]:
PERIODS = period_iterator(year = ['2026'],start_m = 0, stop_m = 6)

PERIODS

['202601', '202602', '202603', '202604', '202605', '202606']

In [7]:
from pathlib import Path
from urllib.request import urlretrieve
from zipfile import ZipFile

file_name = f"JC-{PERIOD}-citibike-tripdata.zip"

output_dir = Path(OUTPUT_DIR)
output_dir.mkdir(exist_ok=True)

zip_path = output_dir / file_name


## Dowloading the Zip file
url = f"{CITIBIKE_INDEX_URL}/{file_name}"

print(f"Downloading: {url}")

print(f"Saved ZIP file to: {zip_path}")


print(f"Extracted files into: {output_dir}")

Downloading: https://s3.amazonaws.com/tripdata/JC-202606-citibike-tripdata.zip
Saved ZIP file to: ..\data\JC-202606-citibike-tripdata.zip
Extracted files into: ..\data

In [14]:
urlretrieve(url, zip_path)

with ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(output_dir)
    
zip_path.unlink()
print("ZIP file removed.")

ZIP file removed.

In [11]:
from pathlib import Path
from zipfile import ZipFile
from io import BytesIO

output_dir = Path(OUTPUT_DIR)
output_dir.mkdir(parents=True, exist_ok=True)

for i in PERIODS:
    urls = [
    f"{CITIBIKE_INDEX_URL}/JC-{i}-citibike-tripdata.csv.zip",
    f"{CITIBIKE_INDEX_URL}/JC-{i}-citibike-tripdata.zip",
]

    last_error = None

    for url in urls:
        try:
            print(f"Trying: {url}")

            response = requests.get(url, timeout=30)
            response.raise_for_status()

            with ZipFile(BytesIO(response.content), "r") as zip_ref:
                zip_ref.extractall(output_dir)

            print(f"Success: {url}")
            break

        except Exception as e:
            print(f"Failed: {url}")
            last_error = e

Trying: https://s3.amazonaws.com/tripdata/JC-202601-citibike-tripdata.csv.zip
Failed: https://s3.amazonaws.com/tripdata/JC-202601-citibike-tripdata.csv.zip
Trying: https://s3.amazonaws.com/tripdata/JC-202601-citibike-tripdata.zip
Failed: https://s3.amazonaws.com/tripdata/JC-202601-citibike-tripdata.zip
Trying: https://s3.amazonaws.com/tripdata/JC-202602-citibike-tripdata.csv.zip
Failed: https://s3.amazonaws.com/tripdata/JC-202602-citibike-tripdata.csv.zip
Trying: https://s3.amazonaws.com/tripdata/JC-202602-citibike-tripdata.zip
Failed: https://s3.amazonaws.com/tripdata/JC-202602-citibike-tripdata.zip
Trying: https://s3.amazonaws.com/tripdata/JC-202603-citibike-tripdata.csv.zip
Failed: https://s3.amazonaws.com/tripdata/JC-202603-citibike-tripdata.csv.zip
Trying: https://s3.amazonaws.com/tripdata/JC-202603-citibike-tripdata.zip
Failed: https://s3.amazonaws.com/tripdata/JC-202603-citibike-tripdata.zip
Trying: https://s3.amazonaws.com/tripdata/JC-202604-citibike-tripdata.csv.zip
Failed: https://s3.amazonaws.com/tripdata/JC-202604-citibike-tripdata.csv.zip
Trying: https://s3.amazonaws.com/tripdata/JC-202604-citibike-tripdata.zip
Failed: https://s3.amazonaws.com/tripdata/JC-202604-citibike-tripdata.zip
Trying: https://s3.amazonaws.com/tripdata/JC-202605-citibike-tripdata.csv.zip
Failed: https://s3.amazonaws.com/tripdata/JC-202605-citibike-tripdata.csv.zip
Trying: https://s3.amazonaws.com/tripdata/JC-202605-citibike-tripdata.zip
Failed: https://s3.amazonaws.com/tripdata/JC-202605-citibike-tripdata.zip
Trying: https://s3.amazonaws.com/tripdata/JC-202606-citibike-tripdata.csv.zip
Failed: https://s3.amazonaws.com/tripdata/JC-202606-citibike-tripdata.csv.zip
Trying: https://s3.amazonaws.com/tripdata/JC-202606-citibike-tripdata.zip
Failed: https://s3.amazonaws.com/tripdata/JC-202606-citibike-tripdata.zip

In [12]:
from pathlib import Path
from urllib.request import urlretrieve
from zipfile import ZipFile
from urllib.request import urlretrieve
from urllib.error import HTTPError, URLError

CITIBIKE_INDEX_URL = "https://s3.amazonaws.com/tripdata"
OUTPUT_DIR = "../data/citibike"
output_dir = Path(OUTPUT_DIR)
output_dir.mkdir(exist_ok=True)


for i in PERIODS:

    try:
        file_name = f"JC-{i}-citibike-tripdata.csv.zip"
        url = f"{CITIBIKE_INDEX_URL}/{file_name}"

        zip_path = output_dir / file_name
        urlretrieve(url, zip_path)

    except (HTTPError, URLError, FileNotFoundError):
        file_name = f"JC-{i}-citibike-tripdata.zip"
        url = f"{CITIBIKE_INDEX_URL}/{file_name}"

        zip_path = output_dir / file_name
        urlretrieve(url, zip_path)

    with ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(output_dir)
    print(f'{file_name}  Extracted')
    zip_path.unlink()
    print(f"{file_name} removed.")

JC-202601-citibike-tripdata.zip  Extracted
JC-202601-citibike-tripdata.zip removed.
JC-202602-citibike-tripdata.csv.zip  Extracted
JC-202602-citibike-tripdata.csv.zip removed.
JC-202603-citibike-tripdata.csv.zip  Extracted
JC-202603-citibike-tripdata.csv.zip removed.
JC-202604-citibike-tripdata.zip  Extracted
JC-202604-citibike-tripdata.zip removed.
JC-202605-citibike-tripdata.csv.zip  Extracted
JC-202605-citibike-tripdata.csv.zip removed.
JC-202606-citibike-tripdata.csv.zip  Extracted
JC-202606-citibike-tripdata.csv.zip removed.

In [15]:
import shutil

shutil.rmtree(output_dir / "__MACOSX")

In [16]:
import glob
import numpy as np
import pandas as pd

file_names = glob.glob(f'{OUTPUT_DIR}/*.csv')



dfs = []
cols = []
for file_name in file_names:
    df = pd.read_csv(file_name)
    print(df.columns, 2*"||",len(df.columns))

    cols.append(list(df.columns))
    dfs.append(df)

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13

In [17]:
citibike_df = pd.concat(dfs)
citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,40.742677,-74.051789,member
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,40.711130,-74.078900,member
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member

In [18]:
citibike_df.to_csv(f'{OUTPUT_DIR}/JC/JC2026.csv', index=False)

In [19]:
citibike_df = pd.read_csv("../data/citibike/JC/JC2026.csv")

citibike_df. head ()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,40.742677,-74.051789,member
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,40.711130,-74.078900,member
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member

In [20]:
print (citibike_df)

                  ride_id  rideable_type               started_at  \
0        880A0159BA5275FB  electric_bike  2025-01-16 17:50:49.136
1        1A5E1E274B2AF0AD  electric_bike  2025-01-31 06:10:41.818
2        EA9928D3C05B8377   classic_bike  2025-01-09 16:42:50.213
3        3C42C367750B9292  electric_bike  2025-01-21 16:14:14.398
4        94D3B0265A7BDE1F   classic_bike  2025-01-30 16:38:18.840
...                   ...            ...                      ...
1418438  DDCC16C0541F379B  electric_bike  2026-06-17 00:08:40.697
1418439  63E5BDCB0E6B66F8   classic_bike  2026-06-24 18:26:29.824
1418440  08693F34F752A9CE  electric_bike  2026-06-17 00:01:18.305
1418441  6914EA3CD9787D17   classic_bike  2026-06-07 12:51:01.894
1418442  524A4D471D0AB1FC  electric_bike  2026-06-02 17:58:09.236

                        ended_at            start_station_name  \
0        2025-01-16 17:57:00.710                       Hilltop
1        2025-01-31 06:22:09.499                       Hilltop
2        2025-01-09 17:04:12.870                       Hilltop
3        2025-01-21 16:37:10.458                       Hilltop
4        2025-01-30 17:04:08.166                       Hilltop
...                          ...                           ...
1418438  2026-06-17 00:14:56.642                Van Vorst Park
1418439  2026-06-24 18:36:57.407                Van Vorst Park
1418440  2026-06-17 00:13:53.479  West Side Ave & Stegman Pkwy
1418441  2026-06-07 12:59:32.790       Communipaw & Berry Lane
1418442  2026-06-02 18:02:54.842                Lafayette Park

        start_station_id                          end_station_name  \
0                  JC019                            Pershing Field
1                  JC019                            Jackson Square
2                  JC019  Hoboken Terminal - Hudson St & Hudson Pl
3                  JC019  Hoboken Terminal - Hudson St & Hudson Pl
4                  JC019  Hoboken Terminal - Hudson St & Hudson Pl
...                  ...                                       ...
1418438            JC035                       Garfield Light Rail
1418439            JC035                       Garfield Light Rail
1418440            JC131                       Garfield Light Rail
1418441            JC084                       Garfield Light Rail
1418442            JC078                       Garfield Light Rail

        end_station_id  start_lat  start_lng    end_lat    end_lng  \
0                JC024  40.731169 -74.057574  40.742677 -74.051789
1                JC063  40.731169 -74.057574  40.711130 -74.078900
2                HB101  40.731169 -74.057574  40.735938 -74.030305
3                HB101  40.731169 -74.057574  40.735938 -74.030305
4                HB101  40.731169 -74.057574  40.735938 -74.030305
...                ...        ...        ...        ...        ...
1418438          JC119  40.718489 -74.047727  40.710526 -74.070112
1418439          JC119  40.718489 -74.047727  40.710526 -74.070112
1418440          JC119  40.710870 -74.093680  40.710526 -74.070112
1418441          JC119  40.714358 -74.066611  40.710526 -74.070112
1418442          JC119  40.713464 -74.062859  40.710526 -74.070112

        member_casual
0              member
1              member
2              member
3              member
4              member
...               ...
1418438        member
1418439        member
1418440        casual
1418441        member
1418442        member

[1418443 rows x 13 columns]

In [21]:
citibike_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')

Cleaniing the data

In [22]:
citibike_df["started_at"] = pd.to_datetime(
    citibike_df["started_at"],
    errors="coerce"
)

citibike_df["ended_at"] = pd.to_datetime(
    citibike_df["ended_at"],
    errors="coerce"
)

In [23]:
citibike_df["ride_date"] = citibike_df["started_at"].dt.date

citibike_df["ride_date"] = pd.to_datetime(
    citibike_df["ride_date"],
    errors="coerce"
)

citibike_df[
    [
        "ride_id",
        "started_at",
        "ended_at",
        "ride_date"
    ]
].head()

            ride_id              started_at                ended_at  ride_date
0  880A0159BA5275FB 2025-01-16 17:50:49.136 2025-01-16 17:57:00.710 2025-01-16
1  1A5E1E274B2AF0AD 2025-01-31 06:10:41.818 2025-01-31 06:22:09.499 2025-01-31
2  EA9928D3C05B8377 2025-01-09 16:42:50.213 2025-01-09 17:04:12.870 2025-01-09
3  3C42C367750B9292 2025-01-21 16:14:14.398 2025-01-21 16:37:10.458 2025-01-21
4  94D3B0265A7BDE1F 2025-01-30 16:38:18.840 2025-01-30 17:04:08.166 2025-01-30

In [24]:
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME")

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

In [25]:
from sqlalchemy import create_engine, text

engine = create_engine(DATABASE_URL)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/citibike)

In [35]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT version();"))
    print(result.fetchone()[0])

PostgreSQL 17.0 (Debian 17.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

In [36]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT PostGIS_Version();"))
    print(result.fetchone()[0])

3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

In [38]:
citibike_df.to_sql(
    name="jersey_city",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=50_000,
    method="multi"
)

1418443

In [39]:
query = """
SELECT
    *
FROM jersey_city
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_date
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,40.742677,-74.051789,member,2025-01-16
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,40.711130,-74.078900,member,2025-01-31
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,2025-01-09
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,2025-01-21
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,2025-01-30
5,9F58D1A2D274211B,electric_bike,2025-01-26 12:41:21.306,2025-01-26 12:50:06.079,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,2025-01-26
6,06E081ED7FFC3B9A,electric_bike,2025-01-14 07:46:19.544,2025-01-14 07:54:25.887,Hilltop,JC019,Morris Canal,JC072,40.731169,-74.057574,40.712419,-74.038526,member,2025-01-14
7,A2933F641B0B4756,electric_bike,2025-01-01 17:28:06.205,2025-01-01 17:35:36.233,Hilltop,JC019,Glenwood Ave,JC094,40.731169,-74.057574,40.727551,-74.071061,member,2025-01-01
8,5A29AAD1161A2DC7,electric_bike,2025-01-13 12:33:51.980,2025-01-13 12:58:04.250,4 St & River St,HB611,Clinton St & Grand St,5303.06,40.740814,-74.027406,40.715595,-73.987030,casual,2025-01-13
9,598F2567309571D5,electric_bike,2025-01-05 19:10:58.189,2025-01-05 19:18:46.106,Dixon Mills,JC076,Pershing Field,JC024,40.721630,-74.049968,40.742677,-74.051789,member,2025-01-05

Load Weather Data

In [40]:
DATA_DIR = Path("../data/citibike/JC")

weather_path = DATA_DIR / "jersey_weather_2026.csv"

In [41]:
import pandas as pd
import requests

lat = 40.7178
lng = -74.0431

start_date = "2025-01-01"
end_date = "2025-12-31"

url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude": lat,
    "longitude": lng,
    "start_date": start_date,
    "end_date": end_date,
    "daily": [
        "temperature_2m_max",
        "temperature_2m_min",
        "temperature_2m_mean",
        "precipitation_sum",
        "rain_sum",
        "snowfall_sum",
        "wind_speed_10m_max"
    ],
    "timezone": "America/New_York"
}

response = requests.get(url, params=params)
response.raise_for_status()

data = response.json()

weather_daily = pd.DataFrame(data["daily"])
weather_daily["date"] = pd.to_datetime(weather_daily["time"])
weather_daily = weather_daily.drop(columns="time")

weather_daily.head()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

In [76]:
weather_daily.to_csv('../data/citibike/JC/jersey_weather_2026.csv', index = False)

In [77]:
weather_daily["date"] = pd.to_datetime(weather_daily["date"])

weather_daily.dtypes

temperature_2m_max            float64
temperature_2m_min            float64
temperature_2m_mean           float64
precipitation_sum             float64
rain_sum                      float64
snowfall_sum                  float64
wind_speed_10m_max            float64
date                   datetime64[us]
dtype: object

In [78]:
weather_df = pd.read_csv(weather_path)

weather_df.head()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

Convert Date Column

In [79]:
weather_df["date"] = pd.to_datetime(
    weather_df["date"],
    errors="coerce"
)

weather_df.head()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

In [80]:
#| echo: true

weather_df.to_sql(
    name="jersey_weather",
    con=engine,
    if_exists="replace",
    index=False
)

365

In [81]:
query = """
SELECT
    *
FROM jersey_weather
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.00,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.00,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.00,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.00,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.00,19.9,2025-01-05
5,-1.6,-4.5,-2.3,1.7,0.0,1.19,16.7,2025-01-06
6,-3.0,-8.7,-5.2,0.0,0.0,0.00,29.9,2025-01-07
7,-2.5,-6.6,-4.3,0.0,0.0,0.00,25.4,2025-01-08
8,-1.5,-6.8,-4.2,0.0,0.0,0.00,29.0,2025-01-09
9,3.3,-3.9,-0.9,0.0,0.0,0.00,22.5,2025-01-10

Geographic

In [83]:
trip_demo = pd.DataFrame({
    "ride_id": list(range(1, 21)),

    "start_station": [
        "Station A", "Station A", "Station A", "Station A", "Station A",
        "Station B", "Station B", "Station B", "Station B",
        "Station C", "Station C", "Station C",
        "Station D", "Station D", "Station D",
        "Station E", "Station E",
        "Station A", "Station B", "Station C"
    ],

    "end_station": [
        "Station B", "Station B", "Station B", "Station C", "Station C",
        "Station A", "Station A", "Station C", "Station D",
        "Station A", "Station B", "Station E",
        "Station A", "Station C", "Station E",
        "Station A", "Station D",
        "Station E", "Station E", "Station D"
    ],

    "started_at": pd.to_datetime([
        "2026-01-01 08:00", "2026-01-01 08:15", "2026-01-01 08:30",
        "2026-01-01 09:00", "2026-01-01 09:20",
        "2026-01-01 10:00", "2026-01-01 10:15", "2026-01-01 10:40",
        "2026-01-01 11:00",
        "2026-01-01 11:30", "2026-01-01 12:00", "2026-01-01 12:20",
        "2026-01-01 13:00", "2026-01-01 13:30", "2026-01-01 14:00",
        "2026-01-01 14:30", "2026-01-01 15:00",
        "2026-01-01 15:30", "2026-01-01 16:00", "2026-01-01 16:30"
    ]),

    "ended_at": pd.to_datetime([
        "2026-01-01 08:10", "2026-01-01 08:28", "2026-01-01 08:42",
        "2026-01-01 09:18", "2026-01-01 09:35",
        "2026-01-01 10:12", "2026-01-01 10:30", "2026-01-01 10:55",
        "2026-01-01 11:18",
        "2026-01-01 11:48", "2026-01-01 12:14", "2026-01-01 12:45",
        "2026-01-01 13:20", "2026-01-01 13:48", "2026-01-01 14:20",
        "2026-01-01 14:55", "2026-01-01 15:22",
        "2026-01-01 15:58", "2026-01-01 16:25", "2026-01-01 16:50"
    ]),

    "member_casual": [
        "member", "member", "casual", "member", "casual",
        "member", "member", "casual", "member",
        "casual", "member", "casual",
        "member", "casual", "member",
        "casual", "member",
        "member", "casual", "member"
    ]
})

trip_demo

,ride_id,start_station,end_station,started_at,ended_at,member_casual
0,1,Station A,Station B,2026-01-01 08:00:00,2026-01-01 08:10:00,member
1,2,Station A,Station B,2026-01-01 08:15:00,2026-01-01 08:28:00,member
2,3,Station A,Station B,2026-01-01 08:30:00,2026-01-01 08:42:00,casual
3,4,Station A,Station C,2026-01-01 09:00:00,2026-01-01 09:18:00,member
4,5,Station A,Station C,2026-01-01 09:20:00,2026-01-01 09:35:00,casual
5,6,Station B,Station A,2026-01-01 10:00:00,2026-01-01 10:12:00,member
6,7,Station B,Station A,2026-01-01 10:15:00,2026-01-01 10:30:00,member
7,8,Station B,Station C,2026-01-01 10:40:00,2026-01-01 10:55:00,casual
8,9,Station B,Station D,2026-01-01 11:00:00,2026-01-01 11:18:00,member
9,10,Station C,Station A,2026-01-01 11:30:00,2026-01-01 11:48:00,casual
10,11,Station C,Station B,2026-01-01 12:00:00,2026-01-01 12:14:00,member
11,12,Station C,Station E,2026-01-01 12:20:00,2026-01-01 12:45:00,casual
12,13,Station D,Station A,2026-01-01 13:00:00,2026-01-01 13:20:00,member
13,14,Station D,Station C,2026-01-01 13:30:00,2026-01-01 13:48:00,casual
14,15,Station D,Station E,2026-01-01 14:00:00,2026-01-01 14:20:00,member
15,16,Station E,Station A,2026-01-01 14:30:00,2026-01-01 14:55:00,casual
16,17,Station E,Station D,2026-01-01 15:00:00,2026-01-01 15:22:00,member
17,18,Station A,Station E,2026-01-01 15:30:00,2026-01-01 15:58:00,member
18,19,Station B,Station E,2026-01-01 16:00:00,2026-01-01 16:25:00,casual
19,20,Station C,Station D,2026-01-01 16:30:00,2026-01-01 16:50:00,member

In [84]:
station_coordinates = pd.DataFrame({
    "station": [
        "Station A",
        "Station B",
        "Station C",
        "Station D",
        "Station E"
    ],
    "lat": [
        40.735,
        40.751,
        40.742,
        40.728,
        40.760
    ],
    "lng": [
        -73.991,
        -73.977,
        -73.985,
        -73.970,
        -73.995
    ]
})

station_coordinates

     station     lat     lng
0  Station A  40.735 -73.991
1  Station B  40.751 -73.977
2  Station C  40.742 -73.985
3  Station D  40.728 -73.970
4  Station E  40.760 -73.995

In [85]:
trip_demo = (
    trip_demo
    .merge(
        station_coordinates,
        left_on="start_station",
        right_on="station",
        how="left"
    )
    .rename(columns={
        "lat": "start_lat",
        "lng": "start_lng"
    })
    .drop(columns="station")
    .merge(
        station_coordinates,
        left_on="end_station",
        right_on="station",
        how="left"
    )
    .rename(columns={
        "lat": "end_lat",
        "lng": "end_lng"
    })
    .drop(columns="station")
)

trip_demo.head()

,ride_id,start_station,end_station,started_at,ended_at,member_casual,start_lat,start_lng,end_lat,end_lng
0,1,Station A,Station B,2026-01-01 08:00:00,2026-01-01 08:10:00,member,40.735,-73.991,40.751,-73.977
1,2,Station A,Station B,2026-01-01 08:15:00,2026-01-01 08:28:00,member,40.735,-73.991,40.751,-73.977
2,3,Station A,Station B,2026-01-01 08:30:00,2026-01-01 08:42:00,casual,40.735,-73.991,40.751,-73.977
3,4,Station A,Station C,2026-01-01 09:00:00,2026-01-01 09:18:00,member,40.735,-73.991,40.742,-73.985
4,5,Station A,Station C,2026-01-01 09:20:00,2026-01-01 09:35:00,casual,40.735,-73.991,40.742,-73.985

In [86]:
map_center = [
    pd.concat([trip_demo["start_lat"], trip_demo["end_lat"]]).mean(),
    pd.concat([trip_demo["start_lng"], trip_demo["end_lng"]]).mean()
]

map_center

[np.float64(40.7427), np.float64(-73.9841)]

In [87]:
trip_demo["duration_min"] = (
    trip_demo["ended_at"] - trip_demo["started_at"]
).dt.total_seconds() / 60

trip_demo[[
    "ride_id",
    "start_station",
    "end_station",
    "started_at",
    "ended_at",
    "duration_min"
]].head()

,ride_id,start_station,end_station,started_at,ended_at,duration_min
0,1,Station A,Station B,2026-01-01 08:00:00,2026-01-01 08:10:00,10.0
1,2,Station A,Station B,2026-01-01 08:15:00,2026-01-01 08:28:00,13.0
2,3,Station A,Station B,2026-01-01 08:30:00,2026-01-01 08:42:00,12.0
3,4,Station A,Station C,2026-01-01 09:00:00,2026-01-01 09:18:00,18.0
4,5,Station A,Station C,2026-01-01 09:20:00,2026-01-01 09:35:00,15.0

In [88]:
trip_demo["date"] = trip_demo["started_at"].dt.date
trip_demo["hour"] = trip_demo["started_at"].dt.hour
trip_demo["day_name"] = trip_demo["started_at"].dt.day_name()
trip_demo["month_name"] = trip_demo["started_at"].dt.month_name()

trip_demo.head()

,ride_id,start_station,end_station,started_at,ended_at,member_casual,start_lat,start_lng,end_lat,end_lng,duration_min,date,hour,day_name,month_name
0,1,Station A,Station B,2026-01-01 08:00:00,2026-01-01 08:10:00,member,40.735,-73.991,40.751,-73.977,10.0,2026-01-01,8,Thursday,January
1,2,Station A,Station B,2026-01-01 08:15:00,2026-01-01 08:28:00,member,40.735,-73.991,40.751,-73.977,13.0,2026-01-01,8,Thursday,January
2,3,Station A,Station B,2026-01-01 08:30:00,2026-01-01 08:42:00,casual,40.735,-73.991,40.751,-73.977,12.0,2026-01-01,8,Thursday,January
3,4,Station A,Station C,2026-01-01 09:00:00,2026-01-01 09:18:00,member,40.735,-73.991,40.742,-73.985,18.0,2026-01-01,9,Thursday,January
4,5,Station A,Station C,2026-01-01 09:20:00,2026-01-01 09:35:00,casual,40.735,-73.991,40.742,-73.985,15.0,2026-01-01,9,Thursday,January

Read GeoJSON with GeoPandas

In [93]:
import geopandas as gpd

In [97]:
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

In [98]:
neighborhood_gdf = gpd.read_file(neighborhood_path)

neighborhood_gdf.head()

,cartodb_id,area_sq_ft,acres,area,neighborhood,color,lon,lat,geometry
0,38,411601381.8,9449.068,Greenville,Port Liberte,NaN,-74.074540,40.694202,"POLYGON ((-74.06862 40.70098, -74.06808 40.696..."
1,52,411601381.8,9449.068,Bergen-Lafayette,LSP Industrial,NaN,-74.062358,40.699189,"POLYGON ((-74.06808 40.69684, -74.06862 40.700..."
2,29,411601381.8,9449.068,West Side,Hackensack,NaN,-74.085147,40.735520,"POLYGON ((-74.07601 40.73822, -74.07781 40.737..."
3,35,411601381.8,9449.068,Bergen-Lafayette,Lafayette,12.0,-74.061279,40.712676,"POLYGON ((-74.056 40.71735, -74.056 40.71692, ..."
4,51,411601381.8,9449.068,Greenville,Jackson Hill,15.0,-74.085503,40.700791,"POLYGON ((-74.07561 40.70233, -74.0758 40.7020..."

In [99]:
neighborhood_gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [100]:
neighborhood_gdf = neighborhood_gdf.to_crs("EPSG:4326")

Inspect Geometry Type

In [101]:
neighborhood_gdf.geom_type.value_counts()

Polygon    53
Name: count, dtype: int64

In [102]:

neighborhood_gdf.to_postgis(
    name="jersey_city_neighborhoods",
    con=engine,
    if_exists="replace",
    index=False
)

Check Spatial Table

In [103]:
query = """
SELECT
    neighborhood,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jersey_city_neighborhoods
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

     neighborhood geometry_type  srid
0    Port Liberte    ST_Polygon  4326
1  LSP Industrial    ST_Polygon  4326
2      Hackensack    ST_Polygon  4326
3       Lafayette    ST_Polygon  4326
4    Jackson Hill    ST_Polygon  4326

Create Station Summary

In [104]:
start_stations = citibike_df[
    [
        "ride_id",
        "start_station_id",
        "start_station_name",
        "start_lat",
        "start_lng"
    ]
].copy()

start_stations = start_stations.rename(
    columns={
        "start_station_id": "station_id",
        "start_station_name": "station_name",
        "start_lat": "lat",
        "start_lng": "lng"
    }
)

start_stations["activity_type"] = "departure"

In [105]:
end_stations = citibike_df[
    [
        "ride_id",
        "end_station_id",
        "end_station_name",
        "end_lat",
        "end_lng"
    ]
].copy()

end_stations = end_stations.rename(
    columns={
        "end_station_id": "station_id",
        "end_station_name": "station_name",
        "end_lat": "lat",
        "end_lng": "lng"
    }
)

end_stations["activity_type"] = "arrival"

In [106]:
station_activity_long = pd.concat(
    [
        start_stations,
        end_stations
    ],
    ignore_index=True
)

station_activity_long = station_activity_long.dropna(
    subset=[
        "station_id",
        "station_name",
        "lat",
        "lng"
    ]
)

In [107]:
station_activity_agg = (
    station_activity_long
    .groupby(
        [
            "station_id",
            "station_name",
            "lat",
            "lng",
            "activity_type"
        ],
        as_index=False
    )
    .agg(
        number_of_rides=("ride_id", "count")
    )
)

In [108]:
station_summary = (
    station_activity_agg
    .pivot_table(
        index=[
            "station_id",
            "station_name",
            "lat",
            "lng"
        ],
        columns="activity_type",
        values="number_of_rides",
        fill_value=0
    )
    .reset_index()
)

station_summary.columns.name = None

station_summary = station_summary.rename(
    columns={
        "departure": "total_departures",
        "arrival": "total_arrivals"
    }
)

if "total_departures" not in station_summary.columns:
    station_summary["total_departures"] = 0

if "total_arrivals" not in station_summary.columns:
    station_summary["total_arrivals"] = 0

station_summary["total_activity"] = (
    station_summary["total_departures"] +
    station_summary["total_arrivals"]
)

station_summary["net_departures"] = (
    station_summary["total_departures"] -
    station_summary["total_arrivals"]
)

station_summary = station_summary.sort_values(
    "total_activity",
    ascending=False
).reset_index(drop=True)

station_summary.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures
0,JC115,Grove St PATH,40.719410,-74.043090,67171.0,64280.0,131451.0,-2891.0
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,37663.0,36943.0,74606.0,-720.0
2,HB106,River St & Newark St,40.736722,-74.029007,37333.0,36139.0,73472.0,-1194.0
3,JC009,Hamilton Park,40.727596,-74.044247,31335.0,31305.0,62640.0,-30.0
4,JC109,Bergen Ave & Sip Ave,40.731009,-74.064437,30082.0,30430.0,60512.0,348.0

Convert Station Summary to GeoDataFrame

In [109]:
station_gdf = gpd.GeoDataFrame(
    station_summary,
    geometry=gpd.points_from_xy(
        station_summary["lng"],
        station_summary["lat"]
    ),
    crs="EPSG:4326"
)

station_gdf.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures,geometry
0,JC115,Grove St PATH,40.719410,-74.043090,67171.0,64280.0,131451.0,-2891.0,POINT (-74.04309 40.71941)
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,37663.0,36943.0,74606.0,-720.0,POINT (-74.0303 40.73594)
2,HB106,River St & Newark St,40.736722,-74.029007,37333.0,36139.0,73472.0,-1194.0,POINT (-74.02901 40.73672)
3,JC009,Hamilton Park,40.727596,-74.044247,31335.0,31305.0,62640.0,-30.0,POINT (-74.04425 40.7276)
4,JC109,Bergen Ave & Sip Ave,40.731009,-74.064437,30082.0,30430.0,60512.0,348.0,POINT (-74.06444 40.73101)

In [112]:
station_gdf.to_postgis(
    name="jc_2026_stations",
    con=engine,
    if_exists="replace",
    index=False
)

Check Station Spatial Table

In [113]:
query = """
SELECT
    station_id,
    station_name,
    total_activity,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jc_2026_stations
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,station_id,station_name,total_activity,geometry_type,srid
0,JC115,Grove St PATH,131451.0,ST_Point,4326
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,74606.0,ST_Point,4326
2,HB106,River St & Newark St,73472.0,ST_Point,4326
3,JC009,Hamilton Park,62640.0,ST_Point,4326
4,JC109,Bergen Ave & Sip Ave,60512.0,ST_Point,4326

List Tables

In [114]:

query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
"""

pd.read_sql(
    query,
    con=engine
)

                  table_name
0          geography_columns
1           geometry_columns
2           jc_2025_stations
3           jc_2026_stations
4                jersey_city
5  jersey_city_neighborhoods
6             jersey_weather
7                     people
8            spatial_ref_sys

## Count Rows for each table

In [115]:

query = """
    SELECT 'jersey_city' AS table_name, COUNT(*) AS row_count FROM jersey_city
    UNION ALL
    SELECT 'jersey_weather' AS table_name, COUNT(*) AS row_count FROM jersey_weather
    UNION ALL
    SELECT 'jersey_city_neighborhoods' AS table_name, COUNT(*) AS row_count FROM jersey_city_neighborhoods
    UNION ALL
    SELECT 'jc_2026_stations' AS table_name, COUNT(*) AS row_count FROM jc_2026_stations;
"""

pd.read_sql(
    query,
    con=engine
)

                  table_name  row_count
0                jersey_city    2421147
1             jersey_weather        365
2  jersey_city_neighborhoods         53
3           jc_2026_stations        566

## Daily Ride Volume

In [116]:
query = """
    SELECT
        started_at::date AS ride_date,
        COUNT(*) AS number_of_rides
    FROM jersey_city
    GROUP BY started_at::date
    ORDER BY ride_date;
"""

daily_rides_sql = pd.read_sql(
    query,
    con=engine
)

daily_rides_sql.head()

    ride_date  number_of_rides
0  2024-12-31                4
1  2025-01-01             2358
2  2025-01-02             3422
3  2025-01-03             3542
4  2025-01-04             2674

## Join Citi Bike and Weather

In [117]:
query = """
SELECT
    c.started_at::date AS ride_date,
    COUNT(*) AS number_of_rides,
    w.temperature_2m_mean,
    w.precipitation_sum,
    w.rain_sum,
    w.snowfall_sum,
    w.wind_speed_10m_max
FROM jersey_city AS c
LEFT JOIN jersey_weather AS w
    ON c.started_at::date = w.date::date
GROUP BY
    c.started_at::date,
    w.temperature_2m_mean,
    w.precipitation_sum,
    w.rain_sum,
    w.snowfall_sum,
    w.wind_speed_10m_max
ORDER BY ride_date;
"""

bike_weather_sql = pd.read_sql(
    query,
    con=engine
)

bike_weather_sql.head()

,ride_date,number_of_rides,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2024-12-31,4,NaN,NaN,NaN,NaN,NaN
1,2025-01-01,2358,7.4,4.5,4.5,0.0,23.2
2,2025-01-02,3422,2.6,0.0,0.0,0.0,25.1
3,2025-01-03,3542,0.4,0.0,0.0,0.0,17.1
4,2025-01-04,2674,-1.4,0.0,0.0,0.0,26.1

## Spatial Join in SQL: Stations to Neighborhoods

In [118]:

query = """
SELECT
    s.station_id,
    s.station_name,
    s.total_departures,
    s.total_arrivals,
    s.total_activity,
    s.net_departures,
    n.neighborhood
FROM jc_2026_stations AS s
JOIN jersey_city_neighborhoods AS n
    ON ST_Within(s.geometry, n.geometry)
ORDER BY s.total_activity DESC;
"""

station_neighborhood_sql = pd.read_sql(
    query,
    con=engine
)

station_neighborhood_sql.head()

,station_id,station_name,total_departures,total_arrivals,total_activity,net_departures,neighborhood
0,JC115,Grove St PATH,64280.0,67171.0,131451.0,-2891.0,Van Vorst Park
1,JC009,Hamilton Park,31305.0,31335.0,62640.0,-30.0,Hamilton Park
2,JC109,Bergen Ave & Sip Ave,30430.0,30082.0,60512.0,348.0,Journal Square
3,JC116,Exchange Pl,28236.0,28198.0,56434.0,38.0,Exchange Place
4,JC066,Newport PATH,27850.0,27782.0,55632.0,68.0,Newport

## Aggregate Station Activity by Neighborhood in SQL

In [119]:

query = """
SELECT
    n.neighborhood,
    COUNT(DISTINCT s.station_id) AS number_of_stations,
    SUM(s.total_departures) AS total_departures,
    SUM(s.total_arrivals) AS total_arrivals,
    SUM(s.total_activity) AS total_activity,
    SUM(s.net_departures) AS net_departures,
    SUM(s.total_activity)::numeric / NULLIF(COUNT(DISTINCT s.station_id), 0) AS avg_activity_per_station
FROM jersey_city_neighborhoods AS n
LEFT JOIN jc_2026_stations AS s
    ON ST_Within(s.geometry, n.geometry)
GROUP BY n.neighborhood
ORDER BY total_activity DESC;
"""

neighborhood_activity_sql = pd.read_sql(
    query,
    con=engine
)

neighborhood_activity_sql.head()

,neighborhood,number_of_stations,total_departures,total_arrivals,total_activity,net_departures,avg_activity_per_station
0,Liberty State Park,0,NaN,NaN,NaN,NaN,NaN
1,Western Slope,0,NaN,NaN,NaN,NaN,NaN
2,LSP Industrial,0,NaN,NaN,NaN,NaN,NaN
3,Canal Crossing,0,NaN,NaN,NaN,NaN,NaN
4,Country Village,0,NaN,NaN,NaN,NaN,NaN

## Create Spatial Indexes

In [120]:

with engine.begin() as connection:
    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_jc_stations_geom
        ON jc_2026_stations
        USING GIST (geometry);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_jersey_city_neighborhoods_geom
        ON jersey_city_neighborhoods
        USING GIST (geometry);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_jc_started_at
        ON jersey_city (started_at);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_weather_date
        ON jersey_weather (date);
    """))

## Create Materialized View with SQLAlchemy

In [121]:
from sqlalchemy import text

In [122]:
create_tableau_materialized_view_sql = """
DROP MATERIALIZED VIEW IF EXISTS mv_tableau_citibike_dashboard;

CREATE MATERIALIZED VIEW mv_tableau_citibike_dashboard AS
WITH ride_base AS (
    SELECT
        c.ride_id,
        c.rideable_type,
        c.member_casual,

        c.started_at,
        c.ended_at,
        c.started_at::date AS ride_date,

        EXTRACT(YEAR FROM c.started_at)::int AS ride_year,
        EXTRACT(QUARTER FROM c.started_at)::int AS ride_quarter,
        EXTRACT(MONTH FROM c.started_at)::int AS ride_month,
        TO_CHAR(c.started_at, 'Month') AS ride_month_name,
        TO_CHAR(c.started_at, 'Day') AS ride_day_of_week,
        EXTRACT(ISODOW FROM c.started_at)::int AS ride_day_number,
        EXTRACT(HOUR FROM c.started_at)::int AS ride_hour,

        CASE
            WHEN EXTRACT(ISODOW FROM c.started_at) IN (6, 7)
                THEN 'Weekend'
            ELSE 'Weekday'
        END AS weekday_type,

        EXTRACT(EPOCH FROM (c.ended_at - c.started_at)) / 60.0 AS ride_duration_minutes,

        c.start_station_id,
        c.start_station_name,
        c.end_station_id,
        c.end_station_name,

        c.start_lat,
        c.start_lng,
        c.end_lat,
        c.end_lng,

        ST_SetSRID(
            ST_MakePoint(c.start_lng, c.start_lat),
            4326
        ) AS start_geom,

        ST_SetSRID(
            ST_MakePoint(c.end_lng, c.end_lat),
            4326
        ) AS end_geom

    FROM jersey_city AS c
    WHERE
        c.ride_id IS NOT NULL
        AND c.started_at IS NOT NULL
        AND c.ended_at IS NOT NULL
        AND c.ended_at > c.started_at
        AND c.start_lat IS NOT NULL
        AND c.start_lng IS NOT NULL
        AND c.end_lat IS NOT NULL
        AND c.end_lng IS NOT NULL
)

SELECT
    r.ride_id,
    r.rideable_type,
    r.member_casual,

    r.started_at,
    r.ended_at,
    r.ride_date,
    r.ride_year,
    r.ride_quarter,
    r.ride_month,
    TRIM(r.ride_month_name) AS ride_month_name,
    TRIM(r.ride_day_of_week) AS ride_day_of_week,
    r.ride_day_number,
    r.ride_hour,
    r.weekday_type,

    r.ride_duration_minutes,

    r.start_station_id,
    r.start_station_name,
    r.end_station_id,
    r.end_station_name,

    r.start_lat,
    r.start_lng,
    r.end_lat,
    r.end_lng,

    start_n.neighborhood AS start_neighborhood,
    end_n.neighborhood AS end_neighborhood,

    ST_Distance(
        r.start_geom::geography,
        r.end_geom::geography
    ) / 1000.0 AS distance_km,

    CASE
        WHEN ST_Distance(r.start_geom::geography, r.end_geom::geography) / 1000.0 < 1
            THEN 'Short'
        WHEN ST_Distance(r.start_geom::geography, r.end_geom::geography) / 1000.0 < 3
            THEN 'Medium'
        ELSE 'Long'
    END AS distance_group,

    CASE
        WHEN r.ride_duration_minutes < 10
            THEN 'Short'
        WHEN r.ride_duration_minutes < 30
            THEN 'Medium'
        ELSE 'Long'
    END AS duration_group,

    w.temperature_2m_max,
    w.temperature_2m_min,
    w.temperature_2m_mean,
    w.precipitation_sum,
    w.rain_sum,
    w.snowfall_sum,
    w.wind_speed_10m_max,

    CASE
        WHEN w.precipitation_sum > 0
            THEN 'Precipitation'
        ELSE 'No Precipitation'
    END AS precipitation_flag,

    CASE
        WHEN w.temperature_2m_mean < 0
            THEN 'Freezing'
        WHEN w.temperature_2m_mean < 10
            THEN 'Cold'
        WHEN w.temperature_2m_mean < 20
            THEN 'Mild'
        ELSE 'Warm'
    END AS temperature_group

FROM ride_base AS r

LEFT JOIN jersey_weather AS w
    ON r.ride_date = w.date::date

LEFT JOIN jersey_city_neighborhoods AS start_n
    ON ST_Within(r.start_geom, start_n.geometry)

LEFT JOIN jersey_city_neighborhoods AS end_n
    ON ST_Within(r.end_geom, end_n.geometry);
"""

In [123]:
with engine.begin() as connection:
    connection.execute(text(create_tableau_materialized_view_sql))

## Check the Materialized View

In [124]:
query = """
SELECT *
FROM mv_tableau_citibike_dashboard
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,rideable_type,member_casual,started_at,ended_at,ride_date,ride_year,ride_quarter,ride_month,ride_month_name,...,duration_group,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,precipitation_flag,temperature_group
0,880A0159BA5275FB,electric_bike,member,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,2025-01-16,2025,1,1,January,...,Short,-0.6,-5.9,-3.2,0.3,0.0,0.21,10.7,Precipitation,Freezing
1,1A5E1E274B2AF0AD,electric_bike,member,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,2025-01-31,2025,1,1,January,...,Medium,6.2,0.7,3.6,10.3,10.3,0.00,13.5,Precipitation,Cold
2,EA9928D3C05B8377,classic_bike,member,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,2025-01-09,2025,1,1,January,...,Medium,-1.5,-6.8,-4.2,0.0,0.0,0.00,29.0,No Precipitation,Freezing
3,3C42C367750B9292,electric_bike,member,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,2025-01-21,2025,1,1,January,...,Medium,-8.4,-15.8,-11.4,0.4,0.0,0.28,10.0,Precipitation,Freezing
4,94D3B0265A7BDE1F,classic_bike,member,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,2025-01-30,2025,1,1,January,...,Medium,1.1,-6.3,-2.0,0.0,0.0,0.00,15.5,No Precipitation,Freezing
5,9F58D1A2D274211B,electric_bike,member,2025-01-26 12:41:21.306,2025-01-26 12:50:06.079,2025-01-26,2025,1,1,January,...,Short,4.1,-5.6,-1.0,0.0,0.0,0.00,15.9,No Precipitation,Freezing
6,06E081ED7FFC3B9A,electric_bike,member,2025-01-14 07:46:19.544,2025-01-14 07:54:25.887,2025-01-14,2025,1,1,January,...,Short,0.4,-3.7,-1.7,0.0,0.0,0.00,21.1,No Precipitation,Freezing
7,A2933F641B0B4756,electric_bike,member,2025-01-01 17:28:06.205,2025-01-01 17:35:36.233,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.00,23.2,Precipitation,Cold
8,5A29AAD1161A2DC7,electric_bike,casual,2025-01-13 12:33:51.980,2025-01-13 12:58:04.250,2025-01-13,2025,1,1,January,...,Medium,6.6,-1.9,1.3,0.0,0.0,0.00,18.3,No Precipitation,Cold
9,598F2567309571D5,electric_bike,member,2025-01-05 19:10:58.189,2025-01-05 19:18:46.106,2025-01-05,2025,1,1,January,...,Short,0.4,-3.6,-2.2,0.0,0.0,0.00,19.9,No Precipitation,Freezing

## Check Number of Rows

In [125]:
query = """
SELECT
    COUNT(*) AS number_of_rows
FROM mv_tableau_citibike_dashboard;
"""

pd.read_sql(
    query,
    con=engine
)

   number_of_rows
0         2411398

## Check Data Quality

In [126]:
query = """
SELECT
    COUNT(*) AS total_rides,

    COUNT(temperature_2m_mean) AS rides_with_weather,
    COUNT(*) - COUNT(temperature_2m_mean) AS rides_missing_weather,

    COUNT(start_neighborhood) AS rides_with_start_neighborhood,
    COUNT(*) - COUNT(start_neighborhood) AS rides_missing_start_neighborhood,

    COUNT(end_neighborhood) AS rides_with_end_neighborhood,
    COUNT(*) - COUNT(end_neighborhood) AS rides_missing_end_neighborhood,

    COUNT(distance_km) AS rides_with_distance,
    COUNT(*) - COUNT(distance_km) AS rides_missing_distance
FROM mv_tableau_citibike_dashboard;
"""

pd.read_sql(
    query,
    con=engine
)

,total_rides,rides_with_weather,rides_missing_weather,rides_with_start_neighborhood,rides_missing_start_neighborhood,rides_with_end_neighborhood,rides_missing_end_neighborhood,rides_with_distance,rides_missing_distance
0,2411398,1998511,412887,1320836,1090562,1310192,1101206,2411398,0

## Create Indexes on the Materialized View

In [46]:
remove_duplicates = """
DELETE FROM jersey_city
WHERE ctid IN (
    SELECT ctid
    FROM (
        SELECT ctid,
            ROW_NUMBER() OVER (PARTITION BY ride_id ORDER BY ctid) as rn
        FROM jersey_city
    ) t
    WHERE t.rn > 1
);
"""

with engine.begin() as connection:
    connection.execute(text(remove_duplicates))

In [48]:
with engine.begin() as connection:
    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_id
        ON mv_tableau_citibike_dashboard (ride_id);
    """))

In [49]:

with engine.begin() as connection:
    connection.execute(text("""
        CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_tableau_ride_id
        ON mv_tableau_citibike_dashboard (ride_id);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_date
        ON mv_tableau_citibike_dashboard (ride_date);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_month
        ON mv_tableau_citibike_dashboard (ride_year, ride_month);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_hour
        ON mv_tableau_citibike_dashboard (ride_hour);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_member_casual
        ON mv_tableau_citibike_dashboard (member_casual);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_rideable_type
        ON mv_tableau_citibike_dashboard (rideable_type);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_start_station
        ON mv_tableau_citibike_dashboard (start_station_name);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_end_station
        ON mv_tableau_citibike_dashboard (end_station_name);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_start_neighborhood
        ON mv_tableau_citibike_dashboard (start_neighborhood);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_end_neighborhood
        ON mv_tableau_citibike_dashboard (end_neighborhood);
    """))

Refresh Materialized View

In [50]:
with engine.begin() as connection:
    connection.execute(
        text("REFRESH MATERIALIZED VIEW mv_tableau_citibike_dashboard;")
    )

##Create Helper Function to Refresh the Dashboard View

In [52]:

def refresh_tableau_dashboard_view(engine, concurrently=False):
    if concurrently:
        refresh_sql = """
        REFRESH MATERIALIZED VIEW CONCURRENTLY mv_tableau_citibike_dashboard;
        """
    else:
        refresh_sql = """
        REFRESH MATERIALIZED VIEW mv_tableau_citibike_dashboard;
        """

    with engine.begin() as connection:
        connection.execute(text(refresh_sql))

Preview Fields for Tableau

In [54]:
query = """
SELECT
    ride_id,
    ride_date,
    ride_month_name,
    ride_day_of_week,
    weekday_type,
    ride_hour,
    rideable_type,
    member_casual,
    start_station_name,
    end_station_name,
    start_neighborhood,
    end_neighborhood,
    ride_duration_minutes,
    duration_group,
    distance_km,
    distance_group,
    temperature_2m_mean,
    temperature_group,
    precipitation_sum,
    precipitation_flag,
    rain_sum,
    snowfall_sum,
    wind_speed_10m_max
FROM mv_tableau_citibike_dashboard
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,ride_date,ride_month_name,ride_day_of_week,weekday_type,ride_hour,rideable_type,member_casual,start_station_name,end_station_name,...,duration_group,distance_km,distance_group,temperature_2m_mean,temperature_group,precipitation_sum,precipitation_flag,rain_sum,snowfall_sum,wind_speed_10m_max
0,880A0159BA5275FB,2025-01-16,January,Thursday,Weekday,17,electric_bike,member,Hilltop,Pershing Field,...,Short,1.368211,Medium,-3.2,Freezing,0.3,Precipitation,0.0,0.21,10.7
1,1A5E1E274B2AF0AD,2025-01-31,January,Friday,Weekday,6,electric_bike,member,Hilltop,Jackson Square,...,Medium,2.863311,Medium,3.6,Cold,10.3,Precipitation,10.3,0.00,13.5
2,99A301983605C8FA,2025-01-02,January,Thursday,Weekday,12,electric_bike,casual,Hilltop,Bergen Ave & Stegman St,...,Medium,3.676304,Long,2.6,Cold,0.0,No Precipitation,0.0,0.00,25.1
3,6DC76F2C3E02A74F,2025-01-13,January,Monday,Weekday,16,electric_bike,member,6 St & Grand St,Madison St & 10 St,...,Short,0.626494,Short,1.3,Cold,0.0,No Precipitation,0.0,0.00,18.3
4,78C1AB7A5683ADBF,2025-01-30,January,Thursday,Weekday,16,electric_bike,member,6 St & Grand St,Monroe St & 11 St,...,Short,0.659386,Short,-2.0,Freezing,0.0,No Precipitation,0.0,0.00,15.5
5,B9105EA418CCCE79,2025-01-14,January,Tuesday,Weekday,16,classic_bike,member,River St & 1 St,Monroe St & 11 St,...,Medium,1.575113,Medium,-1.7,Freezing,0.0,No Precipitation,0.0,0.00,21.1
6,4B4531BA505F2E96,2025-01-07,January,Tuesday,Weekday,18,electric_bike,member,River St & 1 St,Madison St & 10 St,...,Short,1.532069,Medium,-5.2,Freezing,0.0,No Precipitation,0.0,0.00,29.9
7,52385B59943B5C22,2025-01-19,January,Sunday,Weekend,7,classic_bike,member,River St & 1 St,Monroe St & 11 St,...,Medium,1.575113,Medium,0.7,Cold,8.8,Precipitation,0.3,5.95,18.3
8,923723346762C1F9,2025-01-12,January,Sunday,Weekend,13,electric_bike,casual,Hoboken Terminal - Hudson St & Hudson Pl,Madison St & 10 St,...,Short,1.624669,Medium,0.6,Cold,0.0,No Precipitation,0.0,0.00,14.9
9,57D91F76C0DC5606,2025-01-12,January,Sunday,Weekend,0,electric_bike,casual,Hoboken Terminal - Hudson St & Hudson Pl,Madison St & 10 St,...,Short,1.624669,Medium,0.6,Cold,0.0,No Precipitation,0.0,0.00,14.9